# Generated by Django 3.0.4 on 2020-04-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='顧客名')),
                ('gender', models.CharField(choices=[('1', '女性'), ('2', '男性')], max_length=1, verbose_name='性別')),
                ('age', models.IntegerField(blank=True, default=0, verbose_name='年齢')),
            ],
        ),
    ]
