# Generated by Django 3.0.4 on 2020-04-04 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='受講日')),
                ('hour', models.IntegerField(default=0, verbose_name='受講時間(h)')),
                ('charge_yen', models.IntegerField(default=0, verbose_name='支払金額')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member', verbose_name='顧客名')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.Plan', verbose_name='ジャンル')),
            ],
        ),
    ]
