# Generated by Django 3.0.4 on 2020-04-04 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ジャンル')),
                ('basic_charge_yen', models.IntegerField(default=0, verbose_name='基本料金')),
                ('basic_include_hour', models.IntegerField(default=0, verbose_name='基本に含む時間(h)')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPayg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payg_start_hour', models.IntegerField(default=0, verbose_name='従量変動開始時間(h)')),
                ('payg_end_hour', models.IntegerField(default=0, verbose_name='従量変動終了時間(h)')),
                ('payg_charge_yen', models.IntegerField(default=0, verbose_name='従量変動料金')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Plan', verbose_name='ジャンル')),
            ],
        ),
    ]
