# Generated by Django 3.0.4 on 2020-04-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20200404_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpayg',
            name='payg_end_hour',
            field=models.IntegerField(blank=True, null=True, verbose_name='従量変動終了時間(h)'),
        ),
    ]
